# Generated by Django 3.0.12 on 2021-04-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(default='', max_length=10),
        ),
    ]
