# Generated by Django 3.0.12 on 2021-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
